Issue #3 fix
bhavaniravi/airflow-kube-setup pull request #4
Opened 2020-08-23 12:19 UTC by lfreina

Namespace fix for issue #3.

Selector was also added.

2020-08-24 09:43 UTC, bhavaniravi requested changes

2020-08-24 09:43 UTC, bhavaniravi commented on scripts/kube/build/airflow.yaml
> +  - apiGroups: [""]   # "" indicates the core API group
Remove spaces

2020-08-24 09:43 UTC, bhavaniravi commented on scripts/kube/build/airflow.yaml
> +    name: airflow   # Name of the ServiceAccount
Remove spaces

2020-08-24 09:43 UTC, bhavaniravi commented on scripts/kube/build/airflow.yaml
> +          image:
Same as above

2020-08-25 08:53 UTC, lfreina commented on scripts/kube/build/airflow.yaml
> +  - apiGroups: [""]   # "" indicates the core API group
YAML lint was complaining about those spaces but I can remove them. No worries.

2020-08-25 08:54 UTC, lfreina commented
I also took a split into line 57 as the comment was too long. ;D This should do.

2020-08-25 09:47 UTC, merged